name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-16.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download dependencies
      run: |
        mkdir gcc-3.4
        cd gcc-3.4

        wget http://old-releases.ubuntu.com/ubuntu/pool/universe/g/gcc-3.4/cpp-3.4_3.4.6-6ubuntu5_amd64.deb  
        wget http://old-releases.ubuntu.com/ubuntu/pool/universe/g/gcc-3.4/gcc-3.4-base_3.4.6-6ubuntu5_amd64.deb
        wget http://old-releases.ubuntu.com/ubuntu/pool/universe/g/gcc-3.4/g++-3.4_3.4.6-6ubuntu5_amd64.deb  
        wget http://old-releases.ubuntu.com/ubuntu/pool/universe/g/gcc-3.4/libstdc++6-dev_3.4.6-6ubuntu5_amd64.deb
        wget http://old-releases.ubuntu.com/ubuntu/pool/universe/g/gcc-3.4/gcc-3.4_3.4.6-6ubuntu5_amd64.deb

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install gcc-multilib g++-multilib

        cd gcc-3.4

        sudo dpkg -i gcc-3.4-base_3.4.6-6ubuntu5_amd64.deb
        sudo dpkg -i cpp-3.4_3.4.6-6ubuntu5_amd64.deb
        sudo dpkg -i gcc-3.4_3.4.6-6ubuntu5_amd64.deb
        sudo dpkg --force-all -i libstdc++6-dev_3.4.6-6ubuntu5_amd64.deb
        sudo dpkg -i g++-3.4_3.4.6-6ubuntu5_amd64.deb

    - name: Build release
      run: |
        cd dlls
        make CC=gcc-3.4

        mkdir -p ../bugfixedhl-linux/dlls
        cp hl_i386.so ../bugfixedhl-linux/dlls/hl.so
        cp ../network/delta.lst ../bugfixedhl-linux/
        cp ../Readme.txt ../bugfixedhl-linux/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: bugfixedhl-linux
        path: bugfixedhl-linux/

  build-windows:
    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build release
      shell: cmd
      run: |
        msbuild multiplayer.sln -target:hl

        mkdir bugfixedhl-windows
        mkdir bugfixedhl-windows\dlls

        copy dlls\msvc\Debug\hl.dll bugfixedhl-windows\dlls\
        copy network\delta.lst bugfixedhl-windows\
        copy Readme.txt bugfixedhl-windows\

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: bugfixedhl-windows
        path: bugfixedhl-windows/
